In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('Data_Game_Acak.csv')
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [3]:
display(x.head())

    Nama Game  ID Nama Pemain
0  God of War   1        Budi
1  God of War   2        Andi
2  Elden Ring   3        Sari
3  Elden Ring   4        Reza
4     FIFA 24   5        Doni

In [4]:
display(y.head())

0    Action
1    Action
2       RPG
3       RPG
4    Sports
Name: Genre, dtype: object

In [8]:
from sklearn.impute import SimpleImputer
x_imputed = x.replace('', np.nan)
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
x_imputed_array = imputer.fit_transform(x_imputed)
x_imputed_df = pd.DataFrame(x_imputed_array, columns=x.columns)
display(x_imputed_df.head())

    Nama Game ID Nama Pemain
0  God of War  1        Budi
1  God of War  2        Andi
2  Elden Ring  3        Sari
3  Elden Ring  4        Reza
4     FIFA 24  5        Doni

In [7]:
print(f"Jumlah baris di x_imputed_df: {len(x_imputed_df)}")
print(f"Bentuk (rows, columns) x_imputed_df: {x_imputed_df.shape}")

Jumlah baris di x_imputed_df: 15
Bentuk (rows, columns) x_imputed_df: (15, 3)

In [9]:
from sklearn.impute import SimpleImputer
imputer_reapply = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

# Apply imputer to columns 0 to 3 (which covers all columns in x_imputed_df as it has 3 columns)
x_reimputed_array = imputer_reapply.fit_transform(x_imputed_df.iloc[:, 0:3])

# Convert the numpy array back to a DataFrame, preserving column names
x_reimputed_df = pd.DataFrame(x_reimputed_array, columns=x_imputed_df.iloc[:, 0:3].columns)

display(x_reimputed_df.head())

    Nama Game ID Nama Pemain
0  God of War  1        Budi
1  God of War  2        Andi
2  Elden Ring  3        Sari
3  Elden Ring  4        Reza
4     FIFA 24  5        Doni

In [10]:
print(f"Jumlah baris di x_reimputed_df: {len(x_reimputed_df)}")
print(f"Bentuk (rows, columns) x_reimputed_df: {x_reimputed_df.shape}")

Jumlah baris di x_reimputed_df: 15
Bentuk (rows, columns) x_reimputed_df: (15, 3)

### One-Hot Encoding Fitur (x)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 2])], remainder='passthrough')
x_encoded = ct.fit_transform(x_reimputed_df)
display(x_encoded)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 45 stored elements and shape (15, 24)>

### Dataset Splitting (Train/Test)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_encoded, y, test_size=0.2, random_state=1)

print("X_train (first 5 rows):")
display(pd.DataFrame(X_train.toarray()).head()) # Convert sparse matrix to dense for display

print("\nX_test (first 5 rows):")
display(pd.DataFrame(X_test.toarray()).head()) # Convert sparse matrix to dense for display

print("\ny_train (first 5 rows):")
display(y_train.head())

print("\ny_test (first 5 rows):")
display(y_test.head())

X_train (first 5 rows):

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0

X_test (first 5 rows):

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,8.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0

y_train (first 5 rows):

2        RPG
10    Horror
4     Sports
1     Action
13    Sports
Name: Genre, dtype: object

y_test (first 5 rows):

3       RPG
7    Action
6    Action
Name: Genre, dtype: object

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
X_train_dense = X_train.toarray()
X_test_dense = X_test.toarray()
sc = StandardScaler()
X_train_scaled_part = sc.fit_transform(X_train_dense[:, 3:])
X_test_scaled_part = sc.transform(X_test_dense[:, 3:])
X_train_scaled = np.hstack((X_train_dense[:, :3], X_train_scaled_part))
X_test_scaled = np.hstack((X_test_dense[:, :3], X_test_scaled_part))

print("X_train_scaled (first 5 rows):")
display(pd.DataFrame(X_train_scaled).head())

print("\nX_test_scaled (first 5 rows):")
display(pd.DataFrame(X_test_scaled).head())

X_train_scaled (first 5 rows):

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.0,0.0,0.0,3.316625,-0.447214,-0.447214,-0.447214,-0.447214,-0.301511,-0.301511,...,-0.301511,0.0,-0.301511,-0.301511,0.0,0.0,-0.301511,3.316625,-0.301511,-1.161641
1,0.0,0.0,1.0,-0.301511,-0.447214,-0.447214,-0.447214,-0.447214,-0.301511,-0.301511,...,-0.301511,0.0,3.316625,-0.301511,0.0,0.0,-0.301511,-0.301511,-0.301511,0.554013
2,0.0,0.0,0.0,-0.301511,2.236068,-0.447214,-0.447214,-0.447214,-0.301511,-0.301511,...,3.316625,0.0,-0.301511,-0.301511,0.0,0.0,-0.301511,-0.301511,-0.301511,-0.732727
3,0.0,0.0,0.0,-0.301511,-0.447214,-0.447214,2.236068,-0.447214,3.316625,-0.301511,...,-0.301511,0.0,-0.301511,-0.301511,0.0,0.0,-0.301511,-0.301511,-0.301511,-1.376097
4,0.0,0.0,0.0,-0.301511,-0.447214,-0.447214,-0.447214,2.236068,-0.301511,-0.301511,...,-0.301511,0.0,-0.301511,-0.301511,0.0,0.0,-0.301511,-0.301511,-0.301511,1.197383

X_test_scaled (first 5 rows):

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.0,0.0,0.0,3.316625,-0.447214,-0.447214,-0.447214,-0.447214,-0.301511,-0.301511,...,-0.301511,0.0,-0.301511,-0.301511,0.0,1.0,-0.301511,-0.301511,-0.301511,-0.947184
1,0.0,1.0,0.0,-0.301511,-0.447214,-0.447214,-0.447214,-0.447214,-0.301511,-0.301511,...,-0.301511,0.0,-0.301511,-0.301511,1.0,0.0,-0.301511,-0.301511,-0.301511,-0.089357
2,0.0,1.0,0.0,-0.301511,-0.447214,-0.447214,-0.447214,-0.447214,-0.301511,-0.301511,...,-0.301511,1.0,-0.301511,-0.301511,0.0,0.0,-0.301511,-0.301511,-0.301511,-0.303814